name: tickoyakovendors
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted to be more flexible

dependencies:
  cached_network_image: ^3.2.0
  connectivity_plus: ^6.0.5
  dartz: ^0.10.0
  dio: ^5.0.0
  fl_chart: ^0.65.0
  flutter_staggered_animations: ^1.1.1
  equatable: ^2.0.5
  fade_scroll_app_bar: ^0.0.7
  floating_frosted_bottom_bar: ^0.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_chat_types: ^3.4.5
  flutter_chat_ui: ^1.6.15
  flutter_floating_bottom_bar: ^1.2.1+1
  geolocator: ^10.0.0 # Updated to a more recent version
  get_it: ^8.0.0
  injectable: ^2.0.0
  intl: ^0.19.0
  json_annotation: ^4.7.0
  lottie: ^2.7.0
  provider: ^6.1.1
  qr_code_scanner: ^0.7.0
  shared_preferences: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter # Added flutter_test
  hive_generator: ^2.0.0
  json_serializable: ^6.6.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AppIcons (3)/playstore.png"
